### ISSUE TITLE
why use normal attributes?

### ISSUE THREAD

**Issue by majormoses** [eternaltyro/chef-aws-inspector#3]
I am not sure I understand why there is a requirement that these are normal attributes which persist chef client runs. I think during the guard it should be `node` as opposed to `normal` as it should resolve to whatever attribute precedence level is highest. This leave it to the user to decide whether they want to use normal, default, etc. Many AWS envs have ephemeral instances that come up and down on their own this makes it harder to use this cookbook.

**Comment by eternaltyro** [comment]
You're right @majormoses , let me go through the code once. It's been a while since I wrote this and ruby-chef DSL isn't my strong suit!

**Comment by majormoses** [comment]
If you want some help I am more than willing to submit a PR I just wanted to make sure there was not some reason and that this is being actively being maintained before investing the effort.

**Comment by eternaltyro** [comment]
@majormoses  Please do. There's no reason for how things are except probably my ineptitude.
