### ISSUE TITLE
Installing Windows

### ISSUE THREAD

**Issue by chefbob** [eternaltyro/chef-aws-inspector#6]
Any chance of adding windows support to this cookbook?

**Comment by eternaltyro** [comment]
Will work on this. No ETA yet, though. I'm not a Windows person and will take some time for me to test this. Any help is welcome !

**Comment by eternaltyro** [comment]
There's a new WIP branch https://github.com/eternaltyro/chef-aws-inspector/tree/windows-agent

cc: @majormoses

**Comment by chefbob** [comment]
Thanks.  I played around with it some, broke the functions out into separate Linux and Windows cookbooks and put logic into the default recipe to call one or the other.  The windows cookbook is pretty basic.  I can fork the code if you like and share what I've done.

**Comment by chefbob** [comment]
Actually it looks like you've already made a lot of progress.  I'll clone it and give it a try.

**Comment by eternaltyro** [comment]
> you've already made a lot of progress.

I'll be surprised. But please, feel free to raise a pull-request

**Comment by chefbob** [comment]
Working on it now.  I had to make a few minor changes but it is looking good.  Will submit a pull once I'm done testing.

**Comment by chefbob** [comment]
Windows Agent is working and I included test cases.  I also added windows support to .kitchen.yml.  I used the search feature instead of hard coding an AMI ID, to make it easier to work in different regions.  I'm not that good with git so I hope the pull is correct.

**Comment by eternaltyro** [comment]
Pull request: https://github.com/eternaltyro/chef-aws-inspector/pull/7 fixes this issue.

**Comment by chefbob** [comment]
Excellent. I didn’t bump the version so you’ll have to do that.

**Comment by majormoses** [comment]
Sorry for the late response I am on vacation this week. I will review the PR retroactively when I have some time.

**Comment by eternaltyro** [comment]
@chefbob Sure, will do.
