### ISSUE TITLE
Cookbook fails on Linux instance with Chef-Client 13.8.5

### ISSUE THREAD

**Issue by chefbob** [eternaltyro/chef-aws-inspector#8]
An error is thrown when trying to use the cookbook with Chef-Client 13.8.5, "ERROR: Cannot find a resource for windows_package on redhat version 7.4".  It does not seem to honor the only_if platform windows directive.  

       107:  # Install for Windows
       108>> windows_package 'awsagent' do
       109:    source node[:inspector][:win_installer_url]
       110:    installer_type :custom
       111:    options '-silent'
       112:    only_if { platform?('windows') }
       113:  end

This does not happen with the latest 14.x version.  I'll see if there is a way to fix this.

**Comment by eternaltyro** [comment]
Strange. It shouldn't attempt to install a Windows package on Linux. And that too with a guard function! I'll have to read up a little.

**Comment by chefbob** [comment]
It is very strange.  I changed the code to wrap the windows specific code in if statements.  I tested it for both windows and Linux on 13.8.5 and the 14.0.202.  I also updated bumped the version to 0.3.0 and updated the docs to reflect it supports windows 2008 r2 and up.  I'll submit a pull request..

**Comment by chefbob** [comment]
I submitted a pull request.  Would you be able to review and accept it?

**Comment by eternaltyro** [comment]
Thanks, @chefbob . Will do as soon as I can. Give me two days.

**Comment by chefbob** [comment]
@eternaltyro Any chance you can look at this?

**Comment by chefbob** [comment]
@eternaltyro I noticed this was never merged.  Any chance you can merge this or are you no longer maintaining this code?

**Comment by eternaltyro** [comment]
This was merged. Thank you for the changes and apologies for the delay in my response.
